### ISSUE TITLE
Foursquare node allows for output to multiple messages, but does not modify the node's number of outputs.

### ISSUE THREAD

**Issue by lostinthestory** [node-red/node-red-web-nodes#116]
The foursquare node allows the user to select how they would like to receive output. This works great as a single output, or multiple outputs in a single msg object. However, if you want multiple outputs in multiple msg objects, the node itself does not reflect the change in the number of outputs. Therefore, even though the code is passing an array of msgs, you only ever receive the first msg object at the next node. There needs to be an implementation much like how the 'switch' node handles adding an output.

@hbeeken, @hindessm - Am I misreading anything in the code path? It seems foursquare/foursquare.html:279 looks to set the number of node outputs to 1, and it is never changed.

**Comment by knolleary** [comment]
@lostinthestory the node is not expected to vary the number of outputs.

When you pass an array to node.send, each element in that array maps to an output of the node. If one of those elements in the array is itself an array of messages, each of those messages is sent to that output, one at a time.

If you look at where the 4sq node constructs what it passes to node.send in multiple messages case, you can see it builds an array of messages [here](https://github.com/node-red/node-red-web-nodes/blob/master/foursquare/foursquare.js#L153), but then wraps that in array before passing to node.send [here](https://github.com/node-red/node-red-web-nodes/blob/master/foursquare/foursquare.js#L161).

The net effect is that If multiple messages are required, they are all emitted one at a time from the single output.

**Comment by lostinthestory** [comment]
Ah ha!
Thanks @knolleary, I didn't notice it was being passed as a double array despite staring the code staring in the face.
I was trying to use the same approach elsewhere, and could not get more than the first msg unless I added additional output nodes.
