### ISSUE TITLE
Google Directions - missing step in instructions & misleading error message

### ISSUE THREAD

**Issue by ukmoose** [node-red/node-red-web-nodes#124]
as per https://groups.google.com/forum/#!topic/node-red/RZboCmkhmHw

The instructions are missing an important step - actually enabling the API ;-)  

The error message (line 201 in directions.js) is also misleading as it does not reflect the error that Google is returning.

**Comment by knolleary** [comment]
@lostinthestory let me know if you have the bandwidth to look at this and #125

**Comment by dceejay** [comment]
sorry - didn't see it get assigned... was already wip.
