### ISSUE TITLE
Google Directions - node status not updating

### ISSUE THREAD

**Issue by ukmoose** [node-red/node-red-web-nodes#125]
having worked out why the Google directions node was misbehaving I can now successfully return directions information.
However the node-status is stuck as a red donut and "failed".

Refreshing the browser, & turning off & on the "display node status" still has status as "failed" even as results are being returned.

node-red-0 (out): 28 May 11:43:17 - [info] Node-RED version: v0.10.6
node-red-0 (out): 28 May 11:43:17 - [info] Node.js  version: v0.10.28

**Comment by dceejay** [comment]
sorry - didn't see it get assigned... was already wip.
