### ISSUE TITLE
Syntax error in Weather Underground node

### ISSUE THREAD

**Issue by vielmetti** [node-red/node-red-web-nodes#127]
Building a fresh Docker container for a Raspberry Pi tonight and getting this error at module load time:

```
nodered_1   | 22 Jul 05:00:36 - [warn] [wunder] SyntaxError: /usr/local/lib/node_modules/node-red-node-weather-underground/wunder.js:87
nodered_1   |                     else {
nodered_1   |                     ^^^^
```

The build is with node.js 0.12 + Node-RED 0.11 but I am pretty well convinced that this is a simple fix.

**Comment by dceejay** [comment]
HI yes - a } disappeared during the internationalisation efforts... now replaced
