### ISSUE TITLE
Installing Wunderground nodes kills node-node connections in display 

### ISSUE THREAD

**Issue by ukmoose** [node-red/node-red-web-nodes#128]
Node-RED version: v0.10.10
node-red-0 (out): 10 Aug 11:46:02 - [info] Node.js  version: v0.10.28
(running on MacOSX10.10.4)

If I install the wunderground nodes and restart NR the flow is initially displayed as in the first image 
![node-red___192_168_0_22](https://cloud.githubusercontent.com/assets/2537652/9170006/03e42f02-3f57-11e5-8278-12d6475fa0d8.png)
and then a second or two later it "fixes" the position of the nodes but without any connections(image2)
![node-red___192_168_0_22_2](https://cloud.githubusercontent.com/assets/2537652/9170019/212edc2e-3f57-11e5-95a2-f17d494f3034.png)

tested on both Google Chrome 44.0.2403.130 and Safari 8.0.7 (10600.7.12) (both on MacOSX10.10.4)

If I uninstall the wunderground  nodes normality is restored.

Console Errors:

[Error] TypeError: undefined is not a function (evaluating 'this._("wunder.label.wunder")')
	label (undefined, line 19)
	(anonymous function) (red.min.js, line 17)
	(anonymous function) (vendor.js, line 1142)
	Tn (vendor.js, line 1140)
	each (vendor.js, line 1142)
	x (red.min.js, line 17)
	(anonymous function) (red.min.js, line 17)
	emit (red.min.js, line 17)
	onchange (red.min.js, line 17)
	d (red.min.js, line 17)
	b (red.min.js, line 17)
	dispatch (vendor.js, line 3)
	handle (vendor.js, line 3)
[Error] TypeError: null is not an object (evaluating 'e.getAttributeNS')
	attr (vendor.js, line 1142)
	(anonymous function) (red.min.js, line 18)
	(anonymous function) (vendor.js, line 1142)
	Tn (vendor.js, line 1140)
	each (vendor.js, line 1142)
	x (red.min.js, line 17)
	redraw (red.min.js, line 18)
	(anonymous function) (red.min.js, line 16)
	onmessage (red.min.js, line 16)

**Comment by knolleary** [comment]
Think I know what this is, but away from laptop at Legoland for the next
couple days...

Will fix on Wednesday.

**Comment by knolleary** [comment]
Actually, now I've had a second look at your screen shots, you are running an nls'd node in a non-nls'd version of node-red.

You need to either upgrade NR to 0.11.x, or downgrade the node to 0.0.x.

**Comment by ukmoose** [comment]
Ta!  I’ll take a look later.

Might it be useful to include compatability notes in install instructions?  

I followed the npm install instructions for the node as per flows.nodered.org <http://flows.nodered.org/>.  Surely as an end user I shouldn’t have to know any more?

Enjoy playing with all that lego :-)





On 10 Aug 2015, at 15:53, knolleary <notifications@github.com> wrote:

Closed #128 <https://github.com/node-red/node-red-web-nodes/issues/128>.

**Comment by knolleary** [comment]
We added the ability for nodes to declare a minimum version of NR they
support. But the runtime side of that was in 0.11.... Doesn't help with
issues in NR 0.10, but will hopefully help future issues.
