### ISSUE TITLE
openweathermap suddenly returning 'The API call returned invalid JSON

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red-web-nodes#132]
The openweathermap node suddenly stopped working on Oct 10th 2015 at app 5:45AM EST. This showed up on three sites I've deployed in seperate locations. I've set up a test site and the only message I get in the debug or log is:
13 Oct 06:06:34 - [error] [openweathermap:Weather] The API call returned invalid JSON 

any ideas?

**Comment by juggledad** [comment]
Openweathermap now requires an API key (thanks to Mark Setrem for noticing and pointing me towards a get around)

As a get arround (on an rpi) I went to /usr/local/lib/node_modules/node-red-node-openweathermap and edited 'weather.js'. At line 55 you will find this code

        //If the URL is not initialised, there has been an error with the input data,
        //and a node.error is reported.
        if (url) {
            node.status({fill:"blue",shape:"dot",text:"requesting"});

add one line after the 'if (url) {' so you have

        //If the URL is not initialised, there has been an error with the input data,
        //and a node.error is reported.
        if (url) {
            url = url + "&APPID=myapiky";
            node.status({fill:"blue",shape:"dot",text:"requesting"});

changing 'myapikey' to your actual API key and you should be set. This should work for COORDINATES or CITY

**Comment by knolleary** [comment]
We will need to update the node to allow the user to provide their API key.

**Comment by dceejay** [comment]
As the API Key is now mandatory I have updated the node to require use of it... and report errors if it's not set.
