### ISSUE TITLE
openweathermap node missing API field

### ISSUE THREAD

**Issue by tedstriker** [node-red/node-red-web-nodes#133]
The new API Key field is missing in one of the openweathermap nodes

<img width="794" alt="screenshot" src="https://cloud.githubusercontent.com/assets/795203/10476388/9a44e1e8-724d-11e5-92b6-fb3329a265c9.png">

**Comment by tedstriker** [comment]
Why did you close that? There are two nodes within the package and only one provides the API Key field. How is this the desired behavior?

**Comment by dceejay** [comment]
Because the commit that "closed" it added the fix...

**Comment by tedstriker** [comment]
Oops, sorry. Didn't see.
