### ISSUE TITLE
AWS hangs if file does not exist

### ISSUE THREAD

**Issue by Glagnar** [node-red/node-red-web-nodes#136]
I am using the AWS node, and expect an msg.error on the output if a file doesn't exist.
Unfortunately I get no output, and the node hangs.
The debug window does show an exception though:
downloadFailed: NoSuchKey: The specified key does not exist.

**Comment by knolleary** [comment]
Just to confirm, which of the aws nodes are you using? They could all probably do with some better error handling, but want to make sure we address your specific issue.

**Comment by Glagnar** [comment]
I am using the Amazon S3 node.

**Comment by knolleary** [comment]
Sorry, I meant are you using the Input, Output or Query node - the aws
module provides all three.
