### ISSUE TITLE
Dropbox notification of changed file

### ISSUE THREAD

**Issue by akobelan** [node-red/node-red-web-nodes#138]
Are their any known issues of not getting notifications of file change events using the Dropbox-Watch node? I'm running node v0.12.7 and Node-Red v0.13.3?

I can download a file from Dropbox. I can upload a file to Dropbox. I'd like to detect when someone updates a file on Dropbox and then trigger a download to Node-Red. 

Any pointers or advice? Even some example flows would be useful.

**Comment by dceejay** [comment]
Hi - no known problems - however it does only check every 15 mins... so as not to not get banned by the Dropbox API. I will move that up to 10 mins. So it takes a while for the first change to come through.

Republished to npm as version 0.1.3, with slightly updated docs to try to make that clear.
