### ISSUE TITLE
OpenWeatherMap Node

### ISSUE THREAD

**Issue by Raminios** [node-red/node-red-web-nodes#14]
<h1>Query Node</h1>
- Weather information pulled immediately from a certain specified location (city or coordinates).

**Options**
- `Location Type` - City or Coordinates. Either makes certain extra options appear.

**_Appears when coordinates is selected:**_
- `Longitude` - For the user to provide the longitudinal degree of the location.
- `Latitude` - For the user to provide the latitudinal degree of the location.

**_Appears when City is selected:**_
- `City` - For the user to provide the current city from which they wish to get the weather
- `Country` - For the user to provide the current country in which that city is located.

<h1> Outputs </h1>

**msg options**
- `payload` A brief verbal description of the current weather, humanly readable.
- `weather` An extremely short description of the current weather (Clouds, Rain, Sun, etc.)
- `detail`. A more detailed expansion on the `weather` description
- `tempk`. The current ground temperature in Kelvin
- `humidity`. The current humidity percentage.
- `maxtemp`. The maximum temperature at the moment.
- `mintemp`. The minimum temperature at the moment
- `windspeed`. The current wind speed in metres per second
- `winddirection`. The current wind direction in meteorological degrees
- `town`. The exact source location for the weather data
- `long`. The longitude of the location from which the weather data has been pulled.
- `lat` The latitude of the location from which the weather data has been pulled.
- `sunrise`. The time at which the sun rose.
- `sunset`. The time at which the sun will set
- `clouds`. The cloud coverage percentage.

**Comment by Ch3fk0ch88** [comment]
Hi, 
on which way i can get the sunrise and sunset?
I all time get:
`msg.sunrise : undefined(undefined)`

**Comment by dceejay** [comment]
err - hmm- they are all properties of the payload... so
  msg.payload.sunrise

**Comment by Ch3fk0ch88** [comment]
Ok, thanks. got it.
