### ISSUE TITLE
Missunderstanding google calendar in node module

### ISSUE THREAD

**Issue by fabe33** [node-red/node-red-web-nodes#142]
Hi,

I don't really understand how the "calendar in node" work, because when i read the code of calendar.js i think that the module wait for an node.input trigger event to query google calendar to retrieve the next event in the calendar, but module only have an output ?

After I launch node-red how the module know when they must querying my google calendar ?

Thanks a lot.

**Comment by dceejay** [comment]
Hi,
questions like this are best asked on the google group mailing list.
Currently the node polls the server every 15 minutes.
