### ISSUE TITLE
node-red-aws with s3 compatible storage

### ISSUE THREAD

**Issue by openStove** [node-red/node-red-web-nodes#145]
Would it be possible to give an option to specify the endpoint, being able to use S3 compatible storage, and not only aws s3 ?

**Comment by number005** [comment]
Any news here?

**Comment by vielmetti** [comment]
The particular interest that I have in this is to use Minio for storage https://github.com/minio/minio which provides an S3-compatible endpoint.

**Comment by dceejay** [comment]
always happy to consider a pull request that adds this.

**Comment by vielmetti** [comment]
The most likely node to adapt to do this is https://github.com/node-red/node-red-web-nodes/blob/master/aws/package.json - the credit there goes to @hindessm who might be able to answer the question of degree of difficulty of implementing this.

**Comment by loispostula** [comment]
Implemented in #309

**Comment by loispostula** [comment]
@dceejay would it be possible to review #309 to make it available upstream?

**Comment by loispostula** [comment]
@openStove You can close this issue I think :)
