### ISSUE TITLE
AWS S3 "Watch" node not working

### ISSUE THREAD

**Issue by tedbarnett** [node-red/node-red-web-nodes#146]
I have been trying to use the "Amazon S3 watch" node v0.1.1 (from http://flows.nodered.org/node/node-red-node-aws) and having no luck with the "watch" functionality. It never fires when a file is added to my S3 bucket. Using the same AWS credentials, I am able to use the S3 "in" node just fine (i.e. specifying a specific file to download from S3), but the Watch node never fires. I see that it connects just fine (watching the Node status messages).  

I see no errors in my log files, so I have no idea what might be the problem. I am running Node-Red on Bluemix. Any thoughts appreciated. My app depends on having this watch feature work correctly. I've attached a screenshot of my node configuration: I've tried all forms of file wildcard to no avail.

![s3 node](https://cloud.githubusercontent.com/assets/694013/16936375/fbda3c70-4d1a-11e6-86d6-db1e8d43c06d.png)

**Comment by tedbarnett** [comment]
Hmm.  It seems to be working now.  Perhaps I had not been patient enough to wait the full 10 minutes between "watch" checks.  I had hoped it would trigger immediately when a new file appeared.

**Comment by shaounak** [comment]
Was looking for a solution to this problem for the last 3 days. Thanks to this thread.
