### ISSUE TITLE
node-red-aws  Crash node-red server, when localfilename not found 

### ISSUE THREAD

**Issue by openStove** [node-red/node-red-web-nodes#147]
When the localfilename reference an unexisting file, the node is crashing the complete nodered server !

> Uncaught Exception: 25 Jul 11:00:30 - Error: ENOENT: no such file or directory, open '/home/pi/Documents/data    at Error (native)

**Comment by knolleary** [comment]
Hi, which node is this in relation to? There are lots in this repository.
