### ISSUE TITLE
node-red-aws  Feature : Output to react on operation succeed or failed

### ISSUE THREAD

**Issue by openStove** [node-red/node-red-web-nodes#148]
I would be interesting to have an output, being able for example to delete the local file, when upload succeed, or retry later on fail....

**Comment by dceejay** [comment]
All 3 aws nodes generate both error and status messages, that can be caught with the catch node, or status node respectively. These can then be used to trigger retries etc... Is that sufficient ?

PS we prefer ideas and requests to be raised and discussed on the Google group prior to raising an issue, unless it is an issue of course.
