### ISSUE TITLE
msg.payload.lon and lat swapped in reply payload.

### ISSUE THREAD

**Issue by johngeffe** [node-red/node-red-web-nodes#152]
The output from the forecast node has the lon and lat coordinates swapped.
search for msg.payload.lon in the forecastio.js file line 102 and 103.

To a lesser degree the description of the payload.lon and payload.lat in the html file are also swapped.
forecastio.html line 187 and 188.

And the readme also has them backwards.

**Comment by dceejay** [comment]
Yikes,
 thanks for spotting that.

**Comment by johngeffe** [comment]
It just occurred to me to look at the other two weather nodes and I found both of them have the same issue with the readmes and html files.  The js files looked ok.
weatherunderground and openweathermaps nodes.
