### ISSUE TITLE
Add temp_minc and temp_maxc?

### ISSUE THREAD

**Issue by smadds** [node-red/node-red-web-nodes#159]
Hi
Could you add celsius versions of min and max temps in the same way that you have added (current) tempc please?

e.g.

 if (jsun.main.hasOwnProperty("temp_max")) { msg.payload.temp_maxc = parseInt(10 * (Number(jsun.main.temp_max) - 273.2))/10; }
if (jsun.main.hasOwnProperty("temp_min")) { msg.payload.temp_minc = parseInt(10 * (Number(jsun.main.temp_min) - 273.2))/10; }

**Comment by knolleary** [comment]
Which node is this related to? There are lots in this repo!

**Comment by smadds** [comment]
Sorry - the MQTT Publish one

**Comment by dceejay** [comment]
do you have a link please ?

**Comment by smadds** [comment]
It's part of the core, so #10 here:
https://github.com/node-red/node-red/tree/master/nodes/core/io
ᐧ


------------------------------
Simon Maddox | CEO | BCMX Ltd

*t:* UK: 01737-887657     USA: 1-631-998-5086
*mob:* +44-7785-504340
*e:* simon.maddox@bcmx.com     *w:* http://bcmx.com

**Comment by dceejay** [comment]
the mqtt node has nothing to do with temperatures max and min...
so I'm going to assume you mean the openweathermap node that I have already patched and released.
