### ISSUE TITLE
 node-red-node-openweathermap started failing 28/12/16 ~4am GMT

### ISSUE THREAD

**Issue by pathwayx99** [node-red/node-red-web-nodes#162]
Since early this morning,  node-red-node-openweathermap started suddenly failing and crashing Node-RED hard. I've made no changes to my setup, which is using this node to look up wind speed and barometric pressure in my city using my API key. This has been working for several months.

It now looks like it's trying to read a property that's undefined, 'lon' (longitude?). I even tried an exception node dedicated to the openweather node, but the exception still doesn't get caught. Here's the relevant part of my syslog. 

Maybe something was changed in the Openweather API?

```
Dec 28 07:26:32 rPiHomeAutomation Node-RED[358]: 28 Dec 07:26:32 - TypeError: Cannot read property 'lon' of undefined
Dec 28 07:26:32 rPiHomeAutomation Node-RED[358]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-red-node-openweathermap/weather.js:115:67)
Dec 28 07:26:32 rPiHomeAutomation Node-RED[358]: at IncomingMessage.emit (events.js:129:20)
Dec 28 07:26:32 rPiHomeAutomation Node-RED[358]: at _stream_readable.js:908:16
Dec 28 07:26:32 rPiHomeAutomation Node-RED[358]: at process._tickCallback (node.js:355:11)
Dec 28 07:26:37 rPiHomeAutomation systemd[1]: nodered.service: main process exited, code=exited, status=1/FAILURE
Dec 28 07:26:38 rPiHomeAutomation systemd[1]: Unit nodered.service entered failed state.
Dec 28 07:26:38 rPiHomeAutomation systemd[1]: nodered.service holdoff time over, scheduling restart.
Dec 28 07:26:38 rPiHomeAutomation systemd[1]: Stopping Node-RED graphical event wiring tool....
Dec 28 07:26:38 rPiHomeAutomation systemd[1]: Starting Node-RED graphical event wiring tool....
Dec 28 07:26:38 rPiHomeAutomation systemd[1]: Started Node-RED graphical event wiring tool..
Dec 28 07:26:57 rPiHomeAutomation Node-RED[967]: Welcome to Node-RED

```

**Comment by mjunghanns** [comment]
I can confirm this behavior. I was able to narrow down the issue a bit.

This crash seems to occur only by triggering the 5-day forcast and 
querying city/country. It does not crash while querying coordinates 
(lat/lon).

I would recommend the following procedures to get restore your 
environment to a working state again:

    1. move the node's directory (node-red-node-openweathermap) out of
    the node_modules directory. That way you can get your node-red
    instance running.

    2. start node-red

    3. remove any "inject once at start" option (if set) that is
    connected to the (now temporarily unknown) OpenWeatherMap-node, to
    avoid crashing the environment right after startup.

    4. stop node-red

    5. relocate the node-red-node-openweathermap directory to the
    node_modules dir

    6. start node-red

    7. navigate to the affected OpenWeathermap node and (without
    triggering it;) ) change the 5-day forecast settings - figure out
    your coordinates and use them instead of the city's and country's name.

    8. Trigger the node for verification. If Node-RED does not crash
    anymore, you should be fine.

It is a good idea to use pm2 to automatically restart your node-red 
instance in case it crashes. But in order to take advantage of pm2 in 
this very case, it could turn out to be a problem auto-injecting the 
node on startup, so you better disable this option until the main reason 
for this failure has eventually been fixed.

I took a quick look at the OpenWeathermap's response and couldn't see 
any obvious errors or such. I will take a closer look tonight if I find 
the time.

I'd like to express my concerns about Node-RED crashing. This should not 
be happening to this extend, just because an API provider is 
malfunctioning or silently changed the way, the API would work. Is there 
any plan to fix this in the core?


Am 28.12.2016 um 06:36 schrieb pathwayx99:

**Comment by dceejay** [comment]
Thanks for looking at this. 
You will note from his log that pathwayx99 is using systemd to restart Node-RED so no need to use pm2 - but yes it will keep trying and failing in a loop.
The problem of asynchronous errors has been discussed before. The problem is that unless the actual library/node handles it, once thrown asynchronously all we can do is trap them at the highest level. At that point it is possible the runtime is now in an uncertain condition, (and we can't tell), so we take the decision to exit (and maybe restart), rather than continue when possibly compromised.

**Comment by pathwayx99** [comment]
Thanks for the swift responses. 

@mjunghanns: As @dceejay mentioned, I indeed am using systemd so no issue with restarting Node-RED. 

Also, due to having had experimented with Node-RED and nasty crashes in the past, I have very few things that auto-inject at the beginning of the flow -- in particular Openweather fires only every two minutes, so I was able this morning to turn off these nodes rather easily and retain functionality in the rest of the flow. But I really do appreciate the suggestions. Thanks!

What I have not tried yet is the resolution with replacing city name with coordinates. I will do so later today and report back here. 

Season's greetings,

Aris

**Comment by pathwayx99** [comment]
I just tried replacing the city with longitude/latitude. I encounter strange behavior. The first and second triggering seems to work without issues. Then it crashed again with the same error. I'm leaving the injection node disabled for now. 

`Dec 28 14:51:34 rPiHomeAutomation Node-RED[1588]: 28 Dec 14:51:34 - [red] Uncaught Exception:
Dec 28 14:51:34 rPiHomeAutomation Node-RED[1588]: 28 Dec 14:51:34 - TypeError: Cannot read property 'lon' of undefined
Dec 28 14:51:34 rPiHomeAutomation Node-RED[1588]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-red-node-openweathermap/weather.js:115:67)
Dec 28 14:51:34 rPiHomeAutomation Node-RED[1588]: at IncomingMessage.emit (events.js:129:20)
Dec 28 14:51:34 rPiHomeAutomation Node-RED[1588]: at _stream_readable.js:908:16
Dec 28 14:51:34 rPiHomeAutomation Node-RED[1588]: at process._tickCallback (node.js:355:11)
Dec 28 14:51:34 rPiHomeAutomation systemd[1]: nodered.service: main process exited, code=exited, status=1/FAILURE
Dec 28 14:51:35 rPiHomeAutomation systemd[1]: Unit nodered.service entered failed state.
Dec 28 14:51:36 rPiHomeAutomation systemd[1]: nodered.service holdoff time over, scheduling restart.
Dec 28 14:51:36 rPiHomeAutomation systemd[1]: Stopping Node-RED graphical event wiring tool....
Dec 28 14:51:36 rPiHomeAutomation systemd[1]: Starting Node-RED graphical event wiring tool....
Dec 28 14:51:36 rPiHomeAutomation systemd[1]: Started Node-RED graphical event wiring tool..
Dec 28 14:51:55 rPiHomeAutomation Node-RED[2481]: Welcome to Node-RED
Dec 28 14:51:55 rPiHomeAutomation Node-RED[2481]: ===================
Dec 28 14:51:55 rPiHomeAutomation Node-RED[2481]: 28 Dec 14:51:55 - [info] Node-RED version: v0.14.6
Dec 28 14:51:55 rPiHomeAutomation Node-RED[2481]: 28 Dec 14:51:55 - [info] Node.js  version: v0.12.6
Dec 28 14:51:55 rPiHomeAutomation Node-RED[2481]: 28 Dec 14:51:55 - [info] Linux 4.4.13+ arm LE
Dec 28 14:51:55 rPiHomeAutomation Node-RED[2481]: 28 Dec 14:51:55 - [info] Loading palette nodes
`

My flow is [here](http://www.tenaron.com/images/flows.png)

As you can see I use two nodes, one for the current FC, one for the 5-day. Setups [here](http://www.tenaron.com/images/openweather1.png) and [here](http://www.tenaron.com/images/openweather2.png).

**Comment by dceejay** [comment]
One thing at a time :-)... which city are you using to make it fail... (as usual it's working here ;-)

**Comment by pathwayx99** [comment]
Ahahah! Of course it does ;) I'm located in Athens, Greece.

**Comment by dceejay** [comment]
Hi - I have push version 0.1.14 to npm... 
and yes - uurgh - there were some missing traps in there... so yeah just a regular old bug, nothing async at all.. should have been caught. 
Can you give it a try and see if that fixes it for you... (still working here - even for Athens... and/or your co-ordinates)

**Comment by pathwayx99** [comment]
Hmmm. Maybe I'm doing something wrong, but I can't seem to get the latest version on my system. I run the following commands:

`sudo service nodered stop`

`sudo npm update -g node-red-node-openweathermap`

`npm list -g node-red-node-openweathermap`

```
/usr/local/lib
└── node-red-node-openweathermap@0.1.13
```

...what am I doing wrong?

**Comment by dceejay** [comment]
hmmm - you shouldn't be installing things globally (-g) unless you really need to
ideally you just need
    cd ~/.node-red && npm i node-red-node-openweathermap
but if you do that now you may end up with two if the -g worked. - so you may need manually find and delete the original one first.

**Comment by knolleary** [comment]
To update globally installed modules, you need to use `npm install -g` not `npm update -g`.

Just one of those npm things.

**Comment by dceejay** [comment]
really ? I thought is was more that you would need `sudo` - but yeah - is a bit vague

**Comment by pathwayx99** [comment]
Live and learn... Thanks @knolleary, I didn't know that and it looks like it did the trick:

```
sudo npm install -g node-red-node-openweathermap
/usr/local/lib
└── node-red-node-openweathermap@0.1.14
```
And it looks like the update also works. I'm getting proper values now and no crashes. Nothing in the syslog or the exception node. I've re-instated the interval injection and left it to run for a few iterations; it all looks good. Thanks for your efforts, everyone.

So. Nothing to see here. Move along ;)
