### ISSUE TITLE
Box upload error

### ISSUE THREAD

**Issue by webfrank** [node-red/node-red-web-nodes#163]
I'm facing this error uploading a file of 50MB:

TypeError: Cannot read property 'message' of undefined
    at Request._callback (/root/.node-red/node_modules/node-red-node-box/box.js:131:58)
    at Request.self.callback (/root/.node-red/node_modules/node-red-node-box/node_modules/request/request.js:123:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/.node-red/node_modules/node-red-node-box/node_modules/request/request.js:1047:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/.node-red/node_modules/node-red-node-box/node_modules/request/request.js:998:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by webfrank** [comment]
After few hours trying to upload a small file I got: 

1|node-red | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|node-red | TimeoutError: operation timed out
1|node-red |     at afterTimeout (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/main/timers.js:16:15)
1|node-red |     at Timeout.timeoutTimeout [as _onTimeout] (/root/.node-red/node_modules/request-promise/node_modules/bluebird/js/main/timers.js:59:9)
1|node-red |     at ontimeout (timers.js:365:14)
1|node-red |     at tryOnTimeout (timers.js:237:5)
1|node-red |     at Timer.listOnTimeout (timers.js:207:5)

1|node-red | 21 Jan 10:40:45 - [warn] [box-credentials:f46b7d80.c4e3b8] trying to refresh token due to expiry
1|node-red | 21 Jan 10:40:46 - [error] [box-credentials:f46b7d80.c4e3b8] refresh token error: undefined

**Comment by webfrank** [comment]
Hi, found the problem, msg.paylod is not used as file source, as per documentation, only msg.localFile. Please update documentation or fix the bug.

Regards

**Comment by dceejay** [comment]
Have clarified the docs (hopefully). If msg.localFile is not specified the actual content of msg.payload is uploaded... ie the actual bytes of msg.payload are saved to a file on box. If you want to upload a file then yes you need to specify msg.localFile

**Comment by dceejay** [comment]
PS - the delay type function you posted to flows.nodered.org can be achieved with the trigger node.

**Comment by webfrank** [comment]
Hi, could you provide an example with the trigger node? What I want to achieve is to wait until no more message of same type arrives. This is necessary as the watch node continues to fires messages during a big tar process but I want the filename only when it completes.

**Comment by dceejay** [comment]
Configure a trigger node like this
![image](https://cloud.githubusercontent.com/assets/5375409/22183486/84e8dd16-e0b7-11e6-9514-ccd29b2b739f.png)

set the time to be longer than any of the rapid updates you expect...  so the extend will then keep it waiting - before finally releasing the last msg that had arrived

**Comment by webfrank** [comment]
I'll try immediately, tnx


In data 22 gennaio 2017 4:31:17 PM Dave Conway-Jones 
<notifications@github.com> ha scritto:

**Comment by webfrank** [comment]
Hi, it works but not for multiple payloads. Every files processed has a 
different payload which should be tracked differently.
Thanks for pointing me on how to use trigger node but unless it can manage 
an array of different payloads it desn't fit my needs.

Tnx a lot


In data 22 gennaio 2017 4:31:17 PM Dave Conway-Jones 
<notifications@github.com> ha scritto:

**Comment by dceejay** [comment]
aha - indeed. I thought the problem was with tracking one big file upload. So yes you would need to handle an array of files in a less trivial manner.
