### ISSUE TITLE
File download coming as double/triple the size

### ISSUE THREAD

**Issue by soumya-github** [node-red/node-red-web-nodes#166]
I am using the S3 in node to download a jpeg and a pdf file. The files are downloaded in correct format but the size is triple or double the actual size on S3. The files are also not opening and showing as corrupt.

**Comment by dceejay** [comment]
Have you set them to be output as binary buffers ?
and saved to files as binary (don't add cr or append to file etc)

In general we prefer how-to questions to teh google group mailing list or slack channels please.

**Comment by dceejay** [comment]
any more feedback ? Did making it binary (rather than utf8) help ?
can we close this now ?

**Comment by soumya-github** [comment]
Yes you can close this now. Somehow it worked in utf-8 only later.

regards,
Soumya
mobility:9903639236

On 24-Mar-2017 2:27 AM, "Dave Conway-Jones" <notifications@github.com>
wrote:

any more feedback ? Did making it binary (rather than utf8) help ?
can we close this now ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/node-red/node-red-web-nodes/issues/166#issuecomment-288857664>,
or mute the thread
