### ISSUE TITLE
Will not accept key

### ISSUE THREAD

**Issue by DuncanAmos** [node-red/node-red-web-nodes#172]
Whatever I try, the key reverts to something with eight characters after hitting 'Deploy' - consequently, it returns an error    _msg : string[43]  "Error parsing response from API: Not Found↵"_

**Comment by knolleary** [comment]
Hi, this repository contains a few different nodes.

Which node are you referring to?

If it's a password field, we never return passwords back to the editor and use an 8 character placeholder to give the indication that a password is known.

As for what's causing the error you are seeing, we'd need to know what node it is
