### ISSUE TITLE
Posting on IG

### ISSUE THREAD

**Issue by samsoft00** [node-red/node-red-web-nodes#173]
Great job, please can this package post on Instagram? Thanks

**Comment by knolleary** [comment]
Last time we looked at this, there was no public api for uploading to Instagram.

**Comment by knolleary** [comment]
I've double checked - as before, there is no public api for uploading to instagram so not a feature we'll be able to add at this time.

https://www.instagram.com/developer/endpoints/media/

**Comment by magiva** [comment]
considering that apps such as https://www.combin.com/ can schedule and post from a pc, is this now possible to be added to the instagram node
