### ISSUE TITLE
Google maps traffic info

### ISSUE THREAD

**Issue by rikki78** [node-red/node-red-web-nodes#175]
I would like to create a function that warns me when the traffic in the morning to work is more busy than x time.
So this node would be very nice for that.

When I made some tests, I've compared the output of the directions node to the actual maps.google.com output. While I see the expected delay due to traffic on maps.google.com, I don't see it in the output from the node.

I've set msg.departure_time to the current time, as without it the node doesn't output duration_in_traffic.
Is there something else I should set to get the right duration?

**Comment by dceejay** [comment]
Hi - not oen I play with often - but happy to take  a Pull Request - or some code topatch in if you are up for some debug ?   I'd start looking around here - https://github.com/node-red/node-red-web-nodes/blob/master/google/directions.js#L147
(on you local version of course)...  though it does look like msg.payload should contain the complete return object and the duration should be an object somewhere like msg.payload.routes[0].legs[0].duration

**Comment by rikki78** [comment]
Hi thanks for your reply
It seems to me the code you have made is all right, as it copies the data from Google to the node. 
Still the output data always seems to be without traffic delays. What do you want me to debug? I'm happy to help.
Perhaps you can try it yourself to see what happens on your installation, so we can exclude possible faults on my installation?

Thanks!

**Comment by rikki78** [comment]
Ha I found it! 
I've injected the time in milliseconds, then it calculates on historical data. Now I've corrected it, it works!

**Comment by dceejay** [comment]
so ok to close this ? 
or is there something we need to add to docs ?

**Comment by rikki78** [comment]
No it is ok to close. In the docs it is clear the time should be in seconds. Thanks!
