### ISSUE TITLE
300000 interval too short

### ISSUE THREAD

**Issue by thorntonr** [node-red/node-red-web-nodes#176]
From what i can see of: 
node-red-web-nodes/weatherunderground/wunder.js

The 300000 interval is too short and since this isn't a configuration option it makes about twice the requests per day that we're allowed at the free pricing level for the API (500 calls a day).

For many uses, this only needs to update every 5 minutes or 15 minutes, this should be a configuration option.

**Comment by thorntonr** [comment]
Nevermind -- i now see there are 2 nodes -- one that updates when a change is detected and then another that is updated when input is received.

**Comment by dceejay** [comment]
The free tier says it is OK for 500 calls per day = one every 3 mins approx 
60 * 60 * 24 / 500 = 172 
So 300 seconds (5 mins) ought to be OK.

https://www.wunderground.com/weather/api/d/pricing.html

**Comment by thorntonr** [comment]
Thanks,  yeah I first used the no-input nodes and went over 500.  Now it's the node with input with 15 min interval and that's enough for testing now.
