### ISSUE TITLE
Weather Underground nodes poll too often

### ISSUE THREAD

**Issue by gwgorman** [node-red/node-red-web-nodes#181]
If you have the 'free' WU account, you are limited to 500 calls/day. These nodes seem to make calls every 5-10 sec, burning through your allocation quickly. 

Would be great if the poll frequency could be set in the node menus as a parameter, or change the node so it only polls when it gets an input (allowing the use of the Timestamp node).

**Comment by dceejay** [comment]
The repeat interval is 300000 mS - ie 5 minutes, so not sure where you are getting 5 to 10 secs from.
You can use the "other" version of the node and use an inject node to call it on an interval of your choosing.

**Comment by gwgorman** [comment]
Ok I'll try the "other" version again. It seemed to also auto-poll but maybe there was something amiss after the Deploy on Bluemix. Took a NR restart to clear the polling completely after I deleted both of the nodes.

**Comment by dceejay** [comment]
Ok - will have a look and tidy it up.

**Comment by gwgorman** [comment]
Thanks Dave.
