### ISSUE TITLE
"Invalid API key" on openweathermap 5-day forecast, current weather works

### ISSUE THREAD

**Issue by clickworkorange** [node-red/node-red-web-nodes#185]
I have put two openweathermap nodes on a flow, both configured with the same API key, both set to city: London, country: United Kingdom. While the "current weather for" node works fine, and outputs a valid response, the "5 day forecast for" node always returns "Invalid API key". At first I thought this might be because you can only request the 5-day forecast a limited number of times/day, and that there would be a delay between registering and having "credits" to call it, but it's now been ~12h since registering and it's still the same. I have tried copying the API key via a text editor to make sure no spurious characters get included, and I have tried accessing the API through a browser with e.g. `http://api.openweathermap.org/data/2.5/forecast?q=London,uk&appid=[myapikey]` which works fine (in fact I get a response with an array of 40 days). What might be the problem here?

**Comment by clickworkorange** [comment]
Found a solution, see https://github.com/node-red/node-red-web-nodes/pull/186

**Comment by clickworkorange** [comment]
Scratch that, payloads not being populated properly. Perhaps property names or JSON structure has changed. Investigating.

**Comment by dceejay** [comment]
closing as PR accepted
