### ISSUE TITLE
Google Calendar end event does not trigger sometimes

### ISSUE THREAD

**Issue by elvetemedve** [node-red/node-red-web-nodes#189]
## The problem

Add a new **Google Calendar In** node to a flow. Configure the node and set **Inject message `at` the `end` of each event**.

### Expected output
A message is emitted at the end of the event.

### Actual output
Sometimes nothing, but most of the time a message as expected.
The node status shows "_querying_".
![node stuck in querying status](https://user-images.githubusercontent.com/596431/30270043-70e0b556-96eb-11e7-92ac-f36fad896002.png)

I can see only these warning messages in the log (but no errors):

> 11 Sep 06:21:23 - [warn] [google-credentials:bd6b2a62.99b2e8] trying to refresh token due to expiry
> 11 Sep 07:21:25 - [warn] [google-credentials:bd6b2a62.99b2e8] trying to refresh token due to expiry
> 11 Sep 08:21:28 - [warn] [google-credentials:bd6b2a62.99b2e8] trying to refresh token due to expiry
> 11 Sep 09:21:34 - [warn] [google-credentials:bd6b2a62.99b2e8] trying to refresh token due to expiry

**Update**: Same thing happened again, this time I have got errors:

> 14 Sep 09:19:18 - [error] [google calendar in:Calendar event ends] Error: Error: read ETIMEDOUT
> 14 Sep 10:00:01 - [warn] [google-credentials:579254a5.4ba3bc] trying to refresh token due to expiry
> 14 Sep 10:01:51 - [error] [google calendar in:Calendar event ends] Error: Error: read ETIMEDOUT
> 14 Sep 11:00:02 - [warn] [google-credentials:579254a5.4ba3bc] trying to refresh token due to expiry
> 14 Sep 11:00:02 - [error] [google calendar in:Calendar event starts] Error 401: {"error":{"errors":[{"domain":"global","reason":"authError","message":"Invalid Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid Credentials"}}
> 14 Sep 12:00:02 - [error] [google calendar in:Calendar event ends] Error 401: {"error":{"errors":[{"domain":"global","reason":"authError","message":"Invalid Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid Credentials"}}
> 14 Sep 12:00:04 - [warn] [google-credentials:579254a5.4ba3bc] trying to refresh token due to expiry
> 14 Sep 13:00:04 - [warn] [google-credentials:579254a5.4ba3bc] trying to refresh token due to expiry
> 14 Sep 13:00:04 - [error] [google calendar in:Calendar event ends] Error 401: {"error":{"errors":[{"domain":"global","reason":"authError","message":"Invalid Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid Credentials"}}
> 14 Sep 13:02:04 - [error] [google calendar in:Calendar event starts] Error: Error: read ETIMEDOUT
> 14 Sep 14:00:13 - [warn] [google-credentials:579254a5.4ba3bc] trying to refresh token due to expiry

**Update 2**: Both nodes stuck in "querying" status this time:

> 28 Sep 10:01:00 - [warn] [google-credentials:579254a5.4ba3bc] trying to refresh token due to expiry
> 28 Sep 10:01:00 - [warn] [google-credentials:579254a5.4ba3bc] trying to refresh token due to expiry
> 28 Sep 10:01:00 - [error] [google-credentials:579254a5.4ba3bc] refresh token error: undefined
> 28 Sep 10:01:00 - [error] [google-credentials:579254a5.4ba3bc] refresh token error: undefined

**Comment by elvetemedve** [comment]
Fixed by PR https://github.com/node-red/node-red-web-nodes/pull/199.

**Comment by dceejay** [comment]
👍
