### ISSUE TITLE
openweathermap calculation kelvin celcius

### ISSUE THREAD

**Issue by siouxme** [node-red/node-red-web-nodes#190]
wrong calculation from kelvin into celius. rouding is wrong or eventually it truncates simply to 1 decimal

Example: {"weather":"Clear","detail":"clear sky","tempk":284.1,"tempc":10.9,"temp_maxc":11.9,"temp_minc":9.9,"humidity":66,"maxtemp":285.15,"mintemp":283.15,"windspeed":1.5,"winddirection":70,"location":"xxx","sunrise":xxxxx,"sunset":xxxxxx,"clouds":0,"description":"The weather in xxxx"}

**Comment by dceejay** [comment]
changed to -273.15
