### ISSUE TITLE
Version 1 stopped working

### ISSUE THREAD

**Issue by RogierQ** [node-red/node-red-web-nodes#192]
Dropbox  stopped working with version 1

The message i get is: 

"Error verifying credentials: Dropbox API error 400 from GET https://api1.dropbox.com/1/account/info :: {"error": "v1_retired"}"

**Comment by knolleary** [comment]
Duplicate #184 - apologies for the inconvenience. We need to update the node to the new api but haven't had the time/resource available to get it done. Given its now actively broken, I will try to get something sorted this weekend.

**Comment by RogierQ** [comment]
Okidoki, thanks, i stop trying to find a solution ;-)
