### ISSUE TITLE
darksky: language selection does not work

### ISSUE THREAD

**Issue by chgerwig** [node-red/node-red-web-nodes#196]
Hi,
I found out that the language selection does not work. Maybe the API has changed?
Please check the code and the API.
Thanks,
Christian

**Comment by dceejay** [comment]
What are the displayed symptoms ? How can it be recreated ?

**Comment by chgerwig** [comment]
the language setting seams to be ignored. Indifferent which language I select in the node red module setting, the reply is always english. 
When I try it with the URL as described in the API docs it works. Also in node red, when I use a http request module.

**Comment by dceejay** [comment]
published fix as 1.1.17

**Comment by chgerwig** [comment]
Thanks!
