### ISSUE TITLE
Openweathermap documentation for 5-day forecast

### ISSUE THREAD

**Issue by smadds** [node-red/node-red-web-nodes#198]
The current documentation implies an array of 5 objects for the 5-day forecast. Maybe it would be helpful to update this to indicate the payload comprises an array of 40 objects, starting at midnight on the current day with each object covering a 3-hour period.

**Comment by palvarez89** [comment]
Thank you for asking this question. Helped me find what is still missing in the published docs here: https://flows.nodered.org/node/node-red-node-openweathermap
