### ISSUE TITLE
language selection in input message of weather node

### ISSUE THREAD

**Issue by vjrj** [node-red/node-red-web-nodes#204]
Would be nice to select also the language in the input message:
https://github.com/node-red/node-red-web-nodes/blob/cd391de6cc143725d5c0ffa6f47af95371cf36bb/openweathermap/weather.js#L231
something like:
```
 language = n.language || msg.language || "en"; 
```

**Comment by knolleary** [comment]
If you wanted to raise a PR with the necessary, tested, changes, then I'm sure we'd consider it.

**Comment by thmeger** [comment]
Yes, some more options would be great.

**Comment by dceejay** [comment]
added ability to use msg.language (if selected in language options)
and added more languages as supported by API.
published as version 0.2.0
