### ISSUE TITLE
Tow typos 'ap-norteast-1' remain

### ISSUE THREAD

**Issue by kazsharp** [node-red/node-red-web-nodes#221]
Hello,

`node-red-web-nodes/aws/aws.html` was edited for the PR(Fix typo (#201)), but Two parts remain.
"amazon s3 in" was fixed.
"amazon s3 in" and "amazon s3" are not fixed.

https://github.com/node-red/node-red-web-nodes/blob/master/aws/aws.html#L101-L102
https://github.com/node-red/node-red-web-nodes/blob/master/aws/aws.html#L164-L165

Thank you

**Comment by dceejay** [comment]
Thanks for spotting.
