### ISSUE TITLE
Google Calender "failed to fetch calendar list: [object Object]"

### ISSUE THREAD

**Issue by simone1999** [node-red/node-red-web-nodes#224]
Hello,
I tried to setup the Google Calender Node, the Auth process worked just fine but the Node have problems with connecting.
the Messages are:
"1. failed attempts. Waiting 100 ms before next attempt." 4 times with rising Delay times
then: "too many refresh attempts, giving up"
and finaly: "failed to fetch calendar list: [object Object]"

I'm running NodeRed over IoBroker on the Raspberry Pi 3.
The key seems to work, google+ api is enabled and the entry in the hosts file has been made.
Also the given Webadress :"http://node-red.example.com:1886/google-credentials/auth/callback" has been entered under the Redirect URIs of the Keysetup for a web Application
I also have tried it with multiple google Accounts and re generatet the Keys multiple times.

I'm not that skilled with the Linux system, therefore I'm doing anything in the Graphical enviroments, but if there is anny Command I can try out for giving you more informations about the Problem, you are welcome to tell them to me.

If I can get yout module working it would be verry good for me.

**Comment by Inversion-NL** [comment]
I'v got the same problem using Node-Red on a Synology in Docker.

**Comment by magnussp** [comment]
Same problem for me. Running Node-Red 0.19.2 and node-red-node-google version 0.1.4.

Anyone has any idea what the problem could be?

**Comment by simone1999** [comment]
I fixed my problem,
It was an quite obviouse mistake, but one which wasn't documentet anywhere.
You not only have to enable the Google+ API, but also the Callender API in the google console!
After I enabled  the Callender API everything startet to work seamlessly!!!!!!!

Hope I was able to fix your Problems also, hava a nice day and lots of fun with your Projects!
