### ISSUE TITLE
Error Message "openweathermap"openweathermap

### ISSUE THREAD

**Issue by trlafleur** [node-red/node-red-web-nodes#239]
from time to time, I get this message from openweathermap:

~~~
22/01/2019, 01:58:29node: Belfast msg : string[26]
"500 Internal error: 500001"
22/01/2019, 02:08:29node: Belfast msg : string[26]
"500 Internal error: 500001"
22/01/2019, 02:18:29node: Belfast msg : string[26]
"500 Internal error: 500001"
22/01/2019, 02:28:29node: Belfast msg : string[26]
"500 Internal error: 500001"
~~~

- [0.19.5 ] Node-RED version:
- [ v10.14.1] node.js version:
- [6.5.0 ] npm version:
- [ RPI] Platform/OS:
- [ ] Browser:

**Comment by dceejay** [comment]
It' an error from their API...
would this make sense ?

https://openweathermap.desk.com/customer/portal/questions/17207111-periodic-internal-error-5-1-
