### ISSUE TITLE
Feature request: Need for rain volume information in node-red-node-openweathermap

### ISSUE THREAD

**Issue by drose28357** [node-red/node-red-web-nodes#241]
### Which node are you reporting an issue on?
node-red-node-openweathermap for node red

### What are the steps to reproduce?
Feature-Request, used for home and garden automation

UserStory : I as a script for automated gardenwatering want to know how much it had rained so that i dont waste water in the garden.

### What happens?
i could not get anny information about rain volumes from msg.payload

### What do you expect to happen?
maybe a different/extended node with an extended msg.payload including 
    rain.rain.1h      Rain volume for the last 1 hour, mm
    rain.rain.3h      Rain volume for the last 3 hours, mm

Why is the payload restricted to some attributes ? OpenQeatherMap provides more information than is contained in actual msg.payload.

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.0-beta.2
- [ ] node.js version: 10.16.0
- [ ] npm version: 6.9.0
- [ ] Platform/OS: Buildroot on raspberry pi
- [ ] Browser: chrome

**Comment by dceejay** [comment]
Did you see the info page for the node ? It finishes with... msg.data - the full JSON returned by the API.
So if it's in there then you should be able to find it.

**Comment by drose28357** [comment]
Ooops i didn't know that. Will check tomorrow morning 
Thank you for the advice!

**Comment by drose28357** [comment]
O.K. i found msg.data. But didn't find the rain element. That might be due to it didn't reinged here in Germenay...

**Comment by aklciot** [comment]
The problem is that the data returned from OpenWeatherMap is not compatable with js variable names, rainfall is returned as `1h` (1 hour) or `3h` (3 hour). But JS vars cannot start with a digit. At least thats my thought

**Comment by Just-another-pleb** [comment]
Ok, just so you don't feel left out.   I raised a similar question recently.

(I didn't think to check before I asked.)

I can extract the data ok on NR now.   I just use a `text` node and make it show:
`{{data.rain["1h"]}} `   Though that is only for the last `1` hour.

But it is a start.   I hope this helps.
