### ISSUE TITLE
node-red-node-weather-underground returns "Can't find city: undefined, undefined."

### ISSUE THREAD

**Issue by carygravel** [node-red/node-red-web-nodes#243]
### Which node are you reporting an issue on?

node-red-node-weather-underground

### What are the steps to reproduce?

Using the latest node-red-rpi docker image and node-red-node-weather-underground, whatever I put in for city and country (e.g. Berlin and Germany), and whether I have city or coordinates selected,

### What happens?

the debug returns

> "Can't find city: undefined, undefined."

### What do you expect to happen?

I would expect the current weather for the city or coordinates to be returned.

### Please tell us about your environment:

- [ ] Node-RED version: 0.20.7
- [ ] node.js version: 8.1.3
- [ ] npm version:5.0.3
- [ ] Platform/OS:Raspbian/Linux
- [ ] Browser:Firefox

**Comment by carygravel** [comment]
Note that I have exactly the same problem with node-red-node-openweathermap. I assume the two issues are related.

**Comment by Paul-Reed** [comment]
Wunderground is now a 'paid for' service, are you signed up to a paid API package.
The free API is discontinued.

**Comment by carygravel** [comment]
I apologise for the noise. I now have things working with openweathermap.
