### ISSUE TITLE
node-red-node-weather-underground End of Service migration

### ISSUE THREAD

**Issue by johnwalicki** [node-red/node-red-web-nodes#253]
Since the [Weather Underground End of Service](https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api) has sunset the old wunderground API, the nodes in node-red-node-weather-underground no longer function correctly.  It is confusing to keep these nodes in the Node-RED flows catalog.

Personal Weather Station owners can get a new API key from the Weather Underground and use an entirely different set of APIs to query their PWS data and free forecast API.

Instead of rewriting node-red-node-weather-underground, I've created a new set of Node-RED nodes called [node-red-contrib-twc-weather](https://flows.nodered.org/node/node-red-contrib-twc-weather).  These nodes are available for PWS owners.  The new package will also support additional TWC forecast APIs.

I propose we either remove node-red-node-weather-underground from npm or update the README to suggest the new node-red-contrib-twc-weather package.

**Comment by johnwalicki** [comment]
Disclosure: While I work for IBM, I don't work in The Weather Company organization.  I just read the PWS API documentation and created new Node-RED nodes.

**Comment by johnwalicki** [comment]
There's a third choice that plays with live wires.  We could bump the version and modify the wunderground and wunderground-in nodes to only display a migration path to the new node-red-contrib-twc-weather nodes.  TWC should have outlined a migration path a year ago.  It would have caused much less grief and acrimony. 

If we agree on one of these paths, I'd do the work and submit a PR.
See the wunderground nodes here
https://github.com/node-red/node-red-web-nodes/tree/master/weatherunderground

**Comment by dceejay** [comment]
Hi John, 
yes more than happy to deprecate the old nodes - can we just use npm deprecate and point at your new version ? But yes we should certainly update the readme to point to yours.

**Comment by johnwalicki** [comment]
I have submitted a Pull Request that modifies the README to recommend node-red-contrib-twc-weather.  https://github.com/node-red/node-red-web-nodes/pull/254

npm says you're the npm package owner and could probably do the npm deprecate  (not certain how that works - not certain if it then disappears from flows.nodered.org)
https://www.npmjs.com/search?q=node-red-node-weather-underground

I tagged my replacement npm package with weather-underground so folks searching for the old name should be able to find the new package.

**Comment by johnwalicki** [comment]
@dceejay The problem was that I mismatched my email addresses on the commits.  Fixed in
https://github.com/node-red/node-red-web-nodes/pull/257
Please review when you get a chance.

**Comment by johnwalicki** [comment]
@knolleary  Thanks for merging https://github.com/node-red/node-red-web-nodes/pull/257
@dceejay Thanks for helping initially. 
Closing this issue as complete.
