### ISSUE TITLE
Valid Open Weather API Key Rejected By Node

### ISSUE THREAD

**Issue by dachshund-digital** [node-red/node-red-web-nodes#262]
This node is useless when it reports a valid open weather api key as invalid.  API works with other solutions but not this one.

**Comment by dceejay** [comment]
sorry for not looking at this - do you have any more information ? version of node-red ? version of this node ? ( I assume it is the node-red-node-openweathermap ? ) . 
As naturally for me it works :-(... 
If you find the file in your ~/.node-red/node_modules/node-red-node-openweathermap directory and look at weather.js line 69 - you can add a `console.log(url);` and restart Node-RED it will print out the url it uses to etch the result... (Obviously don't share the key with us) - but maybe you can spot something else wrong with the request ?

**Comment by nickiv** [comment]
I just catch it @dachshund-digital @dceejay ! The key is not ready to use after creation. As documentation said: "Your API key will be activated automatically, between 10 minutes and 2 hours after your successful registration". Just wait a little bit. From here: https://openweathermap.org/faq

**Comment by lumpidu** [comment]
Close ?
