### ISSUE TITLE
​ Openweathermap fails to install 

### ISSUE THREAD

**Issue by meloazonte** [node-red/node-red-web-nodes#289]
This is the error code im getting.Does anybody know how one can fix this issue?:

16 Dec 02:44:52 - [warn] Installation des Moduls node-red-node-openweathermap ist fehlgeschlagen:
16 Dec 02:44:52 - [warn] ------------------------------------------
16 Dec 02:44:52 - [warn] npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /Users/melvin/.npm/_cacache/content-v2/sha1/b5/fd
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/Users/melvin/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/melvin/.npm/_logs/2021-12-16T01_44_50_655Z-debug-0.log

16 Dec 02:44:52 - [warn] ------------------------------------------
Error: Installation fehlgeschlagen
    at /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/installer.js:285:25
16 Dec 02:44:52 - [error] Error: Installation fehlgeschlagen

**Comment by dceejay** [comment]
Answered on slack - you can safely delete the `.npm` directory, as it will rebuild itself as needed. - but also you should not have been installing nodes using the root (sudo) user so you may also have other issues at some point
