### ISSUE TITLE
openweathermap catchable errors

### ISSUE THREAD

**Issue by hixfield** [node-red/node-red-web-nodes#290]
### Which node are you reporting an issue on?
node-red-node-openweathermap

### What are the steps to reproduce?
fill in an invalid API key (or provoke any other error in the node eg. api call sends error back).

### What happens?
You will notice that the node produces an error message that can be viewed in the debug area of bordered.

### What do you expect to happen?
This error however cannot be caught by node red's catchall node.
Can we update node-red-node-openweathermap so that for every error it detects (not only invalid API Key, but for example if the OpenWeatherMap api sends any error back) it can be caught by the catchall node? This would allow developers to create a flow that can be running and alert any way they want (in my case I send emails) for signalling errors of the api.

**Comment by dceejay** [comment]
All errors should already be catchable, but I can see the API call one isn't.

**Comment by hixfield** [comment]
Thx for such a fast reaction!
