### ISSUE TITLE
Google contacts

### ISSUE THREAD

**Issue by pcadminby** [node-red/node-red-web-nodes#298]
I would really like to have a node for working with Google contacts. To make it easy to get a list of contacts, create\ delete a contact.

**Comment by dceejay** [comment]
Hi - these issues are really for raising problems with existing nodes. Requests for new capabilities are usually discussed on the [discourse forum](https://discourse.nodered.org/) so the widest audience can offer help and suggestions.
I'm going to close this here are there is nothing to fix.
