### ISSUE TITLE
node-red-node-openweathermap update to 1.0.0 -> error

### ISSUE THREAD

**Issue by Becker884** [node-red/node-red-web-nodes#313]
Hi,
after updating to 1.0.0 today I can´t query weather:

`"401 Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."`

Node-RED Version: v3.1.9
Node.js  Version: v20.12.2
Linux 6.8.0-31-generic x64 LE
NPM: 10.5.0

**Comment by Paul-Reed** [comment]
Did you look at the pricing link URL?
You have to sign up to an account with them, but so long as you limit the number of requests you will not be charged.

**Comment by HolgerAusB** [comment]
@FireWizard52 , @dceejay 
I have 'upgraded' to the free plan API v3.0 and now getting '404 internal server error' with OWM-node 1.0.0, when choosing 'current weather only'. But I get results when choosing the combined one.

AFAIK FreePlan v3.0 subscribers have only access to 'onecall' not to 'weather' but you changed the url in code to `.../data/3.0/weather`

I am not sure, but is there an endpoint weather in 3.0?  `...data/3.0/weather`

Or in other words. I think only `onecall` is on v3 yet, If you need to use `weather`, you have still to use `data/2.5/weather`. Maybe I am wrong. But that's how it works here when testing the links with my browser

**Comment by HolgerAusB** [comment]
...and the second node 'openweathermap **in**' with auto-update every 10min does not even have a combined call, so that won't work at all.

**Comment by FireWizard52** [comment]
Created PR #314.

**Comment by HolgerAusB** [comment]
Thank you @FireWizard52. Will there be a combined catch (onecall) for the 10min version, too?

**Comment by FireWizard52** [comment]
Hi @HolgerAusB,

No, unless someone else dives into it. This was a quick fix (even too quick :( ) to solve the upcoming migration from OneCall 2.5 to OneCall 3.0.

Regards

**Comment by dceejay** [comment]
So is 2.5 going away or not ? If not do we need v3 ? If so then surely we need to find the replacement for 2.5 calls ?

**Comment by HolgerAusB** [comment]
@dceejay yes and no ;-) it is just the endpoint 'onecall' where 2.5 goes away. The other API calls stay on 2.5 for now.

From the mails I got on April 16th and 25th:

> We would like to inform you about our plans to complete the migration from One Call 2.5 to One Call 3.0 that started 2 years ago. In line with this, access to One Call 2.5 will be finally closed in June 2024.

**Comment by HolgerAusB** [comment]
and Onecall 3.0 is the only free plan, a new user can subscribe to (since months) and existing users need to do re-subscribe till June

**Comment by Becker884** [comment]
where can I subscribe Onecall 3 for free?
I just get asked to enter my credit card.

**Comment by HolgerAusB** [comment]
Sorry @Becker884 , that is not possible. You need a credit card to subscribe to 'free' Onecall 3.0. You will NOT be charged for the first 1000 API calls per day. If you have more, you pay 0,14 Euro per 100 calls or whatever your currency is.

After you subscribed, you can limit your calls in the 'Billing plans' section. I changed that to 999.

![grafik](https://github.com/node-red/node-red-web-nodes/assets/3876469/093932cc-2ac7-400a-87e2-c637c0e6b00c)

**Comment by Paul-Reed** [comment]
> where can I subscribe Onecall 3 for free?

...which takes us back to my earlier post above -  https://github.com/node-red/node-red-web-nodes/issues/313#issuecomment-2088282352

**Comment by Becker884** [comment]
ok, I entered my creditcard and activated base plan api call 3.0, but it is the same:

![grafik](https://github.com/node-red/node-red-web-nodes/assets/81651521/54cf0208-4f95-40ca-86c8-af4aded5021d)

**Comment by HolgerAusB** [comment]
How long did you wait after subscribing?

**Comment by FireWizard52** [comment]
In my case, it took about 15 minutes after subscription before I received valid data.
