### ISSUE TITLE
Openweathermap node throws uncaught exception if API endpoint is down

### ISSUE THREAD

**Issue by zobalogh** [node-red/node-red-web-nodes#96]
4 Dec 11:40:02 - [red] Uncaught Exception:
4 Dec 11:40:02 - SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/zoltan/git/node-red-web-nodes/weather/weather.js:97:37)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

@Raminios , we should try to handle this gracefully, otherwise it kills the whole of Node-RED.

Thanks! ;)

**Comment by vielmetti** [comment]
Just saw this exact problem happen:

```
23 May 13:14:31 - [red] Uncaught Exception:
23 May 13:14:31 - SyntaxError: Unexpected token /
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/opt/node-red-0.10.6/node_modules/node-red-node-web-nodes/weather/weather.js:79:37)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

as noted at https://registry.hub.docker.com/u/nieleyde/rpi-nodered/

**Comment by dceejay** [comment]
Hi, I think we do catch an overall parse error - so it must be returning partially valid data to get that far.. - Is there a certain town/city lat/lon that provokes the error more easily ? - so i can see what is actually breaking it.
(in meantime I have pushed a fix with more checking for bad data.)

**Comment by vielmetti** [comment]
I'm monitoring Ann Arbor Michigan and Detroit Michigan on a Raspberry Pi which has Node-RED running under Docker. I'm still sorting out Docker and how it's supposed to work...but once I do it should be convenient for testing things out.

**Comment by dceejay** [comment]
With the extra traps in place I do see occasional bad JSON responses - so hopefully no fixed. Going to close for now. please re-open if you see otherwise
